services:
    api:
        image: boyoyodebugs/boyoyo-fastapi
        depends_on:
            - postgres
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=Universe.10
            - DATABASE_NAME=fastapi
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=52bc9c8dd2e31c99d2702d6ec9e0e93226cffffe98c36531b3105eb700e39183
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30


    postgres:
      image: postgres
      environment:
          - POSTGRES_PASSWORD=Universe.10
          - POSTGRES_DB=fastapi

      volumes:
          - postgres-db:/var/lib/postgresql


volumes:
    postgres-db:

        
